version: '3'

volumes:
  logs:
    driver: local

services:

  service:
    build: .
    environment:
      - docker=true
    volumes:
      - ./:/application
      - logs:/application/logs
    depends_on:
      - redis

  nginx:
    image: nginx
    ports:
      - "8888:8888"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application
    depends_on:
      - service

  redis:
    image: redis:alpine
